# ============================================
# RBAC: Permisos mínimos para Tailscale
# ============================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update", "create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-role
subjects:
  - kind: ServiceAccount
    name: tailscale
---
# ============================================
# Secret: Auth Key de Tailscale (crea antes de aplicar)
# ============================================
# kubectl create secret generic tailscale-auth \
#   --from-literal=TS_AUTHKEY='tskey-auth-xxxxxxxxxxxxxxxxxxxx'
# ============================================
# Deployment principal: Gateway Tailscale
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-gateway
  template:
    metadata:
      labels:
        app: tailscale-gateway
    spec:
      serviceAccountName: tailscale
      containers:
      - name: tailscale
        image: tailscale/tailscale:stable
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_MODULE"]
        env:
          - name: TS_AUTHKEY
            valueFrom:
              secretKeyRef:
                name: tailscale-auth
                key: TS_AUTHKEY
          - name: TS_STATE_DIR
            value: /var/lib/tailscale
          - name: TS_EXTRA_ARGS
            value: "--advertise-routes=10.96.0.0/12,10.244.0.0/16 --hostname=k8s-gateway"
        volumeMounts:
          - name: tailscale-state
            mountPath: /var/lib/tailscale
      volumes:
        - name: tailscale-state
          emptyDir: {}