apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state
  namespace: parcial2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-gateway
  template:
    metadata:
      labels:
        app: tailscale-gateway
    spec:
      containers:
        - name: tailscale
          image: tailscale-gateway:with-socat
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
          volumeMounts:
            - name: tailscale-state
              mountPath: /var/lib/tailscale
          command:
            - sh
            - -c
            - |
              echo "Iniciando tailscaled..."
              tailscaled --state=/var/lib/tailscale/tailscaled.state --tun=userspace-networking &
              sleep 5
              tailscale up \
                --authkey=${TS_AUTHKEY} \
                --hostname=minikube-api \
                --accept-dns=false \
                --accept-routes=true \
                --advertise-exit-node
              echo "Iniciando proxy con socat hacia flask-service..."
              socat TCP-LISTEN:5000,fork TCP:flask-service.parcial2.svc.cluster.local:5000 &
              echo "Gateway activo, manteniendo contenedor vivo..."
              tail -f /dev/null
      volumes:
        - name: tailscale-state
          persistentVolumeClaim:
            claimName: tailscale-state
